apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-front-route
  namespace: internal-infra
  labels:
    app: app
    component: frontend-route
spec:
  parentRefs:
    - kind: Gateway
      name: app-gateway
      namespace: internal-infra
      port: 443
  hostnames:
    - "testapi.firecell.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - kind: Service
          name: app-front
          port: 3001
          weight: 100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app-api-route
  namespace: internal-infra
  labels:
    app: app
    component: api-route
spec:
  parentRefs:
    - kind: Gateway
      name: app-gateway
      namespace: internal-infra
      port: 443
  hostnames:
    - "testapi.firecell.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/api"
        - path:
            type: PathPrefix
            value: "/api/"
      backendRefs:
        - kind: Service
          name: app-api
          port: 5001
          weight: 100
